### ISSUE TITLE
APK crash when selecting camera rights

### ISSUE THREAD

**Issue by yuewu0526** [AnshGaikwad/ImageTrackingAR#1]
I am trying the ARCore package in unity for my project. I used your tutorial https://medium.com/dscvitpune/quick-introduction-to-image-tracking-using-ar-foundation-dea7d2fbdfe9 to build the project. First, I build up the project by myself and it can install applications on both IOS and ANDROID devices. However, it is totally black on the screen or crashed once launched. Therefore, I tried the source code from your GitHub https://github.com/AnshGaikwad/ImageTrackingAR. The application is installed on my android device. When it is launched, it asked the authority for the camera. After selection, it also crashed. The above is built based on the unity editor 2021 version. Later I used unity editor 2019 with source code to build. But I failed with Gradle. In the end, I used the APK file in Github. I directly download the APK file on my android phone. It also crashed once the camera authority is selected. I also tried on another android device of the global system, the result is the same.  How to fix this?

**Comment by AnshGaikwad** [comment]
The problem you are facing is mainly because of the incompatible AR Foundation version with your Unity Editor. Please select the right one and it should work fine.
